data = [
    {
        "question": [
            "Petite question : J’aimerais salut",
            "J’aimerais savoir : Est-ce que vous pouvez coucou ?",
            "Je me permets de vous contacter : Pourriez-vous m’indiquer bonjour ?",
            "Bonjour, Je voudrais hello",
            "Salut, Bonjour ?",
            "Rebonjour, Est-ce que salut mobilia ?",
            "S’il vous plaît, Serait-il possible de salut le robot ?",
            "Bonsoir, Tu pourrais rebonjour ?",
            "Salut le robot étape par étape",
            "J’aurais besoin d’un renseignement : Serait-il possible de yo ?",
            "Excuse-moi, Est-ce que salut tout le monde ?",
            "Pouvez-vous m’aider : Tu pourrais bonsoir à vous ?",
            "Serait-il possible de hello mobilia ?",
            "Pardon, Tu pourrais hello mobilia ?",
            "Pardon, Pourriez-vous m’indiquer yo ?",
            "Rebonjour, J’aimerais hey salut",
            "J’aurais besoin d’un renseignement : Je cherche à salut",
            "Rebonjour, Peux-tu bonjour le bot ?",
            "Pardon, Je voudrais hello",
            "Je n’arrive pas à bonjour le bot, pouvez-vous m’aider ?",
            "Petite question : Pourriez-vous hello mobilia ?",
            "Excuse-moi, Salut stp ?",
            "J’aurais besoin d’un renseignement : Je cherche à hello mobilia",
            "Pardon, Tu pourrais salut tout le monde ?",
            "Bonjour, Pourriez-vous m’indiquer bonsoir à vous ?",
            "Bonsoir, Je voudrais hello mobilia",
            "Bonjour rapidement, s’il vous plaît",
            "Coucou au plus vite",
            "Salut s’il te plaît",
            "Salut, Hello",
            "Pouvez-vous m’aider : Salut stp ?",
            "Excuse-moi, Est-ce que hello mobilia ?",
            "Pardon, Hello Mobilia",
            "Bonsoir, Coucou Mobilia ?",
            "Petite question : Pourriez-vous bonsoir à vous ?",
            "Petite question : Bonjour MobiliaBot s’il te plaît",
            "Pardon, Bonsoir",
            "Petite question : J’aimerais salut à toi",
            "S’il te plaît, Peux-tu bonsoir à vous ?",
            "Pouvez-vous m’expliquer comment bonjour le bot ?",
            "Je me permets de vous contacter : J’aimerais hello",
            "Pardon, Hello Mobilia stp",
            "Je me permets de vous contacter : Peux-tu salut tout le monde ?",
            "J’aimerais savoir : Peux-tu salut l’assistant mobilia ?",
            "Bonjour, Est-ce que vous pouvez hello mobilia ?",
            "Rebonjour, Bonsoir à vous s’il te plaît ?",
            "Bonsoir, Bonsoir à vous s’il te plaît ?",
            "Bonsoir, Je voudrais salut mobilia",
            "Pardon, Est-ce que bonsoir à vous ?",
            "S’il vous plaît, Pourriez-vous bonjour ?",
            "J’aurais besoin d’un renseignement : Coucou",
            "Pouvez-vous m’aider : J’aimerais salut l’assistant mobilia",
            "Pardon, Salut le robot",
            "J’aurais besoin d’un renseignement : Je voudrais bonjour le bot",
            "Pouvez-vous m’aider : Bonjour MobiliaBot s’il te plaît",
            "Excuse-moi, Pourriez-vous m’indiquer rebonjour ?",
            "J’aurais besoin d’un renseignement : Salut ?",
            "Pouvez-vous m’aider : Est-ce que salut mobilia ?",
            "Pouvez-vous m’aider : Salut Mobilia s’il vous plaît ?",
            "J’aimerais savoir : Est-ce que vous pouvez rebonjour ?",
            "Je me permets de vous contacter : Bonsoir à vous s’il te plaît",
            "Rebonjour, Pourriez-vous m’indiquer salut tout le monde ?",
            "S’il vous plaît, J’aimerais salut le service client",
            "Bonjour, Tu pourrais salut le robot ?",
            "J’aimerais savoir : Est-ce que salut le robot ?",
            "Rebonjour, Bonjour",
            "Je me permets de vous contacter : Est-ce que vous pouvez coucou mobilia ?",
            "Est-ce que coucou ?",
            "Pouvez-vous m’aider : Pourriez-vous bonjour ?",
            "Pouvez-vous m’aider : Est-ce que hey salut ?",
            "Rebonjour, Je cherche à bonjour mobiliabot",
            "Rebonjour, Est-ce que vous pouvez bonjour mobiliabot ?",
            "J’aimerais savoir : Est-ce que bonjour le bot ?",
            "Pouvez-vous m’aider : J’aimerais bonsoir",
            "Salut, Pourriez-vous hello ?",
            "Salut Mobilia quand vous pouvez",
            "J’aimerais savoir : Pourriez-vous salut le service client ?",
            "Rebonjour, Yo merci",
            "Salut, Pourriez-vous m’indiquer salut mobilia ?",
            "Je me permets de vous contacter : Pourriez-vous salut tout le monde ?"
        ],
        "answer": "Bonjour 👋 Bienvenue chez Mobilia ! Comment puis-je vous aider aujourd’hui ?",
        "action_index": 0
    },
    {
        "question": [
            "Pouvez-vous m’aider : Je cherche à es-tu un conseiller",
            "Pouvez-vous m’aider : Je voudrais tu travailles pour qui",
            "J’aimerais savoir : Tu pourrais explique-moi ton rôle ?",
            "Pourriez-vous m’indiquer parle-moi de toi ?",
            "Bonsoir, Serait-il possible de quel est ton but ?",
            "S’il te plaît, Je voudrais qui t’a créé",
            "Pouvez-vous m’aider : J’aimerais quel est ton but",
            "S’il vous plaît, Est-ce que vous pouvez explique-moi ton rôle ?",
            "Salut, Quel est ton but merci",
            "Bonjour, Est-ce que parle-moi de toi ?",
            "Pouvez-vous m’aider : Serait-il possible de quel est ton but ?",
            "Explique-moi ton rôle merci ?",
            "Je me permets de vous contacter : Tu pourrais tu fais quoi ?",
            "Pouvez-vous m’aider : Je voudrais qui t’a développé",
            "Excuse-moi, Serait-il possible de tu es un vrai humain ?",
            "Je me permets de vous contacter : Est-ce que vous pouvez es-tu un conseiller ?",
            "Tu pourrais que peux-tu faire ?",
            "S’il vous plaît, J’aimerais explique-moi ton rôle",
            "Je me permets de vous contacter : Qui t’a créé",
            "J’aimerais savoir : Tu fais quoi ?",
            "Bonsoir, J’aimerais tu appartiens à mobilia",
            "Je me permets de vous contacter : J’aimerais qui es-tu",
            "Pouvez-vous m’aider : Je voudrais explique-moi ton rôle",
            "Je cherche à explique-moi ton rôle",
            "S’il te plaît, Qui es-tu",
            "Je me permets de vous contacter : Je voudrais tu es un vrai humain",
            "S’il te plaît, Je voudrais que peux-tu faire",
            "Bonjour, Peux-tu t’es qui toi ?",
            "Bonsoir, Est-ce que vous pouvez c’est quoi mobilia ?",
            "J’aimerais savoir : Est-ce que qui es-tu ?",
            "S’il vous plaît, Est-ce que vous pouvez t’es qui toi ?",
            "Bonjour, Serait-il possible de tu es un vrai humain ?",
            "Pouvez-vous m’aider : Je cherche à quel est ton but",
            "Excuse-moi, Tu pourrais qui es-tu ?",
            "Je me permets de vous contacter : Est-ce que vous pouvez tu travailles pour qui ?",
            "J’aurais besoin d’un renseignement : Tu pourrais explique-moi ton rôle ?",
            "Excuse-moi, J’aimerais que fais-tu concrètement",
            "J’aurais besoin d’un renseignement : Tu appartiens à Mobilia",
            "Pardon, Serait-il possible de tu fais partie de l’équipe ?",
            "S’il te plaît, Je cherche à tu appartiens à mobilia",
            "Bonsoir, Pourriez-vous qui es-tu ?",
            "Rebonjour, Pourriez-vous m’indiquer tu fais partie de l’équipe ?",
            "Excuse-moi, Peux-tu tu travailles pour qui ?",
            "Bonjour, Quel est ton but ?",
            "S’il vous plaît, Serait-il possible de parle-moi de toi ?",
            "Excuse-moi, Qui es-tu stp ?",
            "Bonjour, Je cherche à parle-moi de toi",
            "Je me permets de vous contacter : J’aimerais c’est quoi mobilia",
            "S’il te plaît, Pourriez-vous m’indiquer tu fais quoi ?",
            "J’aurais besoin d’un renseignement : Est-ce que vous pouvez tu travailles pour qui ?",
            "Je me demandais : qui t’a développé  ?",
            "Je me permets de vous contacter : Tu pourrais parle-moi de toi ?",
            "J’aurais besoin d’un renseignement : Qui t’a développé svp",
            "Rebonjour, Je cherche à explique-moi ton rôle",
            "Pouvez-vous m’expliquer comment t’es qui toi  ?",
            "Rebonjour, Tu représentes Mobilia merci ?",
            "Je me permets de vous contacter : Est-ce que vous pouvez t’es qui toi ?",
            "Bonsoir, Est-ce que que fais-tu concrètement ?",
            "J’aurais besoin d’un renseignement : Tu pourrais c’est quoi ton job ?",
            "Tu fais quoi",
            "Je me permets de vous contacter : Serait-il possible de tu es un vrai humain ?",
            "Bonsoir, Tu fais quoi svp ?",
            "Pouvez-vous m’aider : Est-ce que vous pouvez tu fais partie de l’équipe ?",
            "Je me permets de vous contacter : Tu représentes Mobilia",
            "S’il te plaît, Que peux-tu faire svp",
            "Je me permets de vous contacter : Peux-tu à quoi sers-tu ?",
            "J’aimerais savoir : Peux-tu quel est ton but ?",
            "J’aimerais savoir : Est-ce que vous pouvez qui t’a développé ?",
            "Bonjour, Serait-il possible de c’est quoi mobilia ?",
            "Est-ce que vous pouvez explique-moi ton rôle ?",
            "J’aimerais savoir : Est-ce que à quoi sers-tu ?",
            "Excuse-moi, Quel est ton rôle exact merci ?",
            "Petite question : Pourriez-vous quel est ton but ?",
            "Je me permets de vous contacter : Quel est ton but",
            "S’il te plaît, Qui t’a développé s’il vous plaît ?",
            "Que peux-tu faire",
            "S’il te plaît, J’aimerais qui es-tu",
            "J’aurais besoin d’un renseignement : J’aimerais qui t’a développé",
            "Bonsoir, Pourriez-vous quel est ton rôle exact ?",
            "J’aurais besoin d’un renseignement : Parle-moi de toi s’il te plaît"
        ],
        "answer": "Je suis MobiliaBot 🤖, votre assistant intelligent pour tout savoir sur nos meubles, livraisons et services.",
        "action_index": 0
    },
    {
        "question": [
            "S’il vous plaît, Pourriez-vous tu peux me montrer vos produits ?",
            "Bonsoir, Tu pourrais tu proposes des bureaux ?",
            "Pardon, Je cherche à je cherche un meuble tv",
            "Rebonjour, Je voudrais avez-vous des fauteuils",
            "S’il vous plaît, Est-ce que avez-vous des fauteuils ?",
            "Excuse-moi, Est-ce que vous pouvez quel type de mobilier proposez-vous ?",
            "Bonjour, Serait-il possible de proposez-vous des luminaires ?",
            "Pouvez-vous m’aider : Je voudrais tu as des étagères",
            "Salut, Est-ce que vous pouvez quels produits vendez-vous ?",
            "Rebonjour, Tu proposes des bureaux ?",
            "J’aimerais savoir : Est-ce que vous pouvez tu proposes des bureaux ?",
            "Rebonjour, Pourriez-vous m’indiquer tu as des chaises ?",
            "Salut, Tu pourrais tu proposes des bureaux ?",
            "Petite question : Je cherche à vous avez des lampes",
            "Je cherche à quels types de meubles avez-vous",
            "Excuse-moi, Vous vendez des lits svp ?",
            "Je veux voir le catalogue stp ?",
            "Je cherche un meuble TV",
            "Bonsoir, Vous vendez des lits ?",
            "Tu as des tables  étape par étape",
            "Pardon, Est-ce que vous pouvez vous avez des lampes ?",
            "J’aurais besoin d’un renseignement : Vous avez des armoires merci",
            "S’il te plaît, J’aimerais tu peux me montrer vos produits",
            "Je voudrais tu proposes quoi",
            "Bonjour, Je cherche à proposez-vous des luminaires",
            "Excuse-moi, Est-ce que vous vendez des meubles en bois ?",
            "Pardon, Est-ce que vous pouvez je cherche une table basse ?",
            "Bonjour, J’aimerais je cherche une table basse",
            "S’il te plaît, Peux-tu avez-vous du mobilier de jardin ?",
            "J’aurais besoin d’un renseignement : J’aimerais vous vendez des meubles en bois",
            "Excuse-moi, Est-ce que tu proposes des bureaux ?",
            "J’aimerais tu as des tables",
            "S’il te plaît, Je voudrais je cherche une table basse",
            "Petite question : Peux-tu tu proposes quoi ?",
            "Vous vendez des lits  rapidement, s’il vous plaît",
            "Excuse-moi, Est-ce que vous avez des lampes ?",
            "Bonjour, Est-ce que je veux voir le catalogue ?",
            "S’il te plaît, Vous vendez des meubles en bois",
            "Pouvez-vous m’aider : Tu pourrais tu peux me montrer vos produits ?",
            "Petite question : Je cherche un meuble TV ?",
            "S’il te plaît, Proposez-vous des luminaires ?",
            "J’aurais besoin d’un renseignement : Tu proposes quoi",
            "Petite question : Tu pourrais avez-vous du mobilier de jardin ?",
            "Rebonjour, Serait-il possible de je cherche une table basse ?",
            "S’il vous plaît, Peux-tu vous avez des lampes ?",
            "Tu as des tables  quand vous pouvez",
            "J’aurais besoin d’un renseignement : Tu pourrais tu as des tables ?",
            "Je n’arrive pas à avez-vous du mobilier de jardin , pouvez-vous m’aider ?",
            "Petite question : Pourriez-vous tu as des chaises ?",
            "Je me permets de vous contacter : Pourriez-vous quel type de mobilier proposez-vous ?",
            "Rebonjour, Tu as des chaises svp",
            "Est-ce que vous pouvez je cherche une table basse ?",
            "Petite question : Pourriez-vous tu as des tables ?",
            "Bonsoir, Tu pourrais tu as des étagères ?",
            "S’il te plaît, Serait-il possible de quels types de meubles avez-vous ?",
            "Rebonjour, Peux-tu je veux voir le catalogue ?",
            "Rebonjour, Tu pourrais vous vendez des lits ?",
            "Je cherche à tu as des chaises",
            "Pardon, Vous avez des canapés stp",
            "Je me demandais : tu as des étagères  ?",
            "Bonjour, Est-ce que vous pouvez tu proposes quoi ?",
            "J’aurais besoin d’un renseignement : Je voudrais quels produits vendez-vous",
            "Besoin d’aide pour quels produits vendez-vous",
            "Bonjour, Je veux voir le catalogue",
            "J’aurais besoin d’un renseignement : Quels produits vendez-vous",
            "S’il vous plaît, Tu pourrais tu as des étagères ?",
            "J’aurais besoin d’un renseignement : Tu pourrais vous avez des lampes ?",
            "Pardon, J’aimerais tu proposes quoi",
            "Est-ce que tu proposes des bureaux ?",
            "Avez-vous des fauteuils  au plus vite",
            "Pardon, Pourriez-vous proposez-vous des luminaires ?",
            "J’aimerais savoir : Je cherche un meuble TV ?",
            "Bonsoir, J’aimerais quels types de meubles avez-vous",
            "S’il vous plaît, Tu pourrais proposez-vous des luminaires ?",
            "Pouvez-vous m’aider : Serait-il possible de avez-vous des fauteuils ?",
            "Je me permets de vous contacter : Peux-tu je cherche une table basse ?",
            "Bonjour, J’aimerais vous avez des canapés",
            "Pardon, Je cherche à je veux voir le catalogue",
            "Pouvez-vous m’aider : Je cherche à quels produits vendez-vous",
            "Petite question : Peux-tu je cherche un meuble tv ?"
        ],
        "answer": "Nous proposons un large choix : tables, chaises, canapés, lits, bureaux, meubles TV, rangements et luminaires 💡.",
        "action_index": 0
    },
    {
        "question": [
            "Rebonjour, Je veux finaliser ma commande",
            "Pouvez-vous m’aider : Je veux finaliser ma commande ?",
            "Je veux acheter ?",
            "Bonsoir, J’aimerais aide-moi à acheter une table",
            "Pourriez-vous m’indiquer je veux acheter un meuble ?",
            "Pardon, Je voudrais je ne trouve pas le bouton de paiement",
            "J’aurais besoin d’un renseignement : Est-ce que comment payer ?",
            "Bonsoir, Pourriez-vous m’indiquer je veux un bureau en bois clair ?",
            "S’il te plaît, Comment confirmer ma commande s’il te plaît",
            "Je me permets de vous contacter : Où dois-je cliquer pour acheter",
            "Bonjour, Aide-moi à acheter une table",
            "Bonjour, Comment valider mon panier svp",
            "Salut, Pourriez-vous je veux finaliser ma commande ?",
            "Excuse-moi, Puis-je commander par téléphone stp",
            "Comment valider mon panier  quand vous pouvez",
            "Est-ce que vous pouvez comment réserver un produit ?",
            "Salut, Je cherche à je veux passer une commande",
            "Bonjour, Je ne trouve pas le bouton de paiement s’il vous plaît ?",
            "Comment passer commande  rapidement, s’il vous plaît",
            "Rebonjour, Je voudrais tu peux m’aider à commander",
            "Pardon, Pourriez-vous m’indiquer je veux acheter un meuble ?",
            "J’aimerais savoir : Pourriez-vous m’indiquer comment payer ?",
            "S’il te plaît, Tu pourrais je veux finaliser ma commande ?",
            "S’il vous plaît, Comment passer commande",
            "Petite question : Je voudrais je veux acheter un canapé",
            "S’il vous plaît, Est-ce que je veux finaliser ma commande ?",
            "Pardon, Pourriez-vous comment faire un achat ?",
            "Salut, Serait-il possible de je souhaite passer une commande ?",
            "Je ne trouve pas le bouton de paiement s’il te plaît",
            "Salut, Je veux acheter un meuble ?",
            "Bonjour, Tu pourrais comment confirmer ma commande ?",
            "Je veux acheter s’il vous plaît",
            "S’il vous plaît, Je voudrais je veux passer une commande",
            "S’il vous plaît, Je voudrais comment faire un achat",
            "Pouvez-vous m’aider : Serait-il possible de je veux finaliser ma commande ?",
            "S’il te plaît, Pourriez-vous comment confirmer ma commande ?",
            "J’aimerais savoir : J’aimerais je veux un bureau en bois clair",
            "Je voudrais comment payer",
            "Pouvez-vous m’aider : Peux-tu comment réserver un produit ?",
            "Pouvez-vous m’aider : Peux-tu je veux finaliser ma commande ?",
            "Bonjour, Est-ce que vous pouvez comment valider mon panier ?",
            "Pardon, Peux-tu comment commander ?",
            "Bonjour, Je veux acheter",
            "Comment valider mon panier",
            "Excuse-moi, Je veux acheter ?",
            "Pardon, Je cherche à comment réserver un produit",
            "J’aurais besoin d’un renseignement : Puis-je commander par téléphone ?",
            "Bonjour, Est-ce que vous pouvez où dois-je cliquer pour acheter ?",
            "Rebonjour, Je voudrais comment passer commande",
            "Rebonjour, Je voudrais comment valider mon panier",
            "Pardon, Je voudrais comment commander",
            "J’aimerais savoir : Pourriez-vous m’indiquer je souhaite passer une commande ?",
            "Bonsoir, Est-ce que comment valider mon panier ?",
            "Salut, Je voudrais comment valider mon panier",
            "Je me permets de vous contacter : Je cherche à où dois-je cliquer pour acheter",
            "Petite question : Je cherche à où dois-je cliquer pour acheter",
            "Bonsoir, Comment passer commande",
            "S’il vous plaît, Pourriez-vous comment valider mon panier ?",
            "Peux-tu tu peux m’aider à commander ?",
            "Pardon, Est-ce que vous pouvez comment faire un achat ?",
            "Pouvez-vous m’aider : Je cherche à où dois-je cliquer pour acheter",
            "Bonjour, Comment passer commande ?",
            "S’il te plaît, Je voudrais comment faire un achat",
            "Pouvez-vous m’aider : J’aimerais je veux finaliser ma commande",
            "S’il te plaît, Puis-je commander par téléphone ?",
            "Je cherche à comment valider mon panier",
            "Je n’arrive pas à comment passer commande , pouvez-vous m’aider ?",
            "Bonjour, Je cherche à je veux acheter un meuble",
            "Petite question : Tu pourrais comment passer commande ?",
            "Pardon, Est-ce que comment faire un achat ?",
            "J’aurais besoin d’un renseignement : Puis-je commander par téléphone",
            "Je me permets de vous contacter : Est-ce que vous pouvez comment passer commande ?",
            "Salut, Je voudrais comment faire un achat",
            "Excuse-moi, Peux-tu je veux acheter ?",
            "Je n’arrive pas à je veux un bureau en bois clair, pouvez-vous m’aider ?",
            "Comment faire un achat  au plus vite",
            "Rebonjour, Est-ce que vous pouvez je ne trouve pas le bouton de paiement ?",
            "Bonjour, Je cherche à où dois-je cliquer pour acheter",
            "Salut, Est-ce que vous pouvez j’ai ajouté au panier et après ?",
            "J’aimerais savoir : J’aimerais je veux finaliser ma commande"
        ],
        "answer": "C’est simple 🛒 : ajoutez vos produits à votre panier, puis validez la commande sur mobilia.fr. Je peux aussi vous guider !",
        "action_index": 0
    },
    {
        "question": [
            "Excuse-moi, Je n’ai toujours rien reçu s’il vous plaît",
            "J’attends un canapé quand vous pouvez",
            "S’il vous plaît, J’aimerais je veux voir le suivi",
            "Rebonjour, Le transporteur ne m’a pas contacté ?",
            "Excuse-moi, Tu pourrais je n’ai toujours rien reçu ?",
            "Je me permets de vous contacter : J’aimerais je veux suivre ma commande",
            "J’aimerais savoir : Tu pourrais ma commande est bloquée ?",
            "Je cherche à je n’ai toujours rien reçu",
            "Pardon, C’est livré quand ?",
            "Pouvez-vous m’aider : Pourriez-vous j’attends un canapé ?",
            "J’aurais besoin d’un renseignement : Je veux voir le suivi",
            "Bonsoir, J’aimerais combien de temps reste-t-il",
            "J’aurais besoin d’un renseignement : Où est mon meuble",
            "Pardon, Tu pourrais mon colis n’est pas arrivé ?",
            "Pardon, Pourriez-vous quand vais-je recevoir ma commande ?",
            "Pardon, Est-ce que vous pouvez je n’ai toujours rien reçu ?",
            "S’il vous plaît, Peux-tu suivi de commande ?",
            "Excuse-moi, Serait-il possible de quand vais-je recevoir ma commande ?",
            "Bonjour, Est-ce que vous pouvez quand la livraison aura lieu ?",
            "Pardon, Tu pourrais quand vais-je recevoir ma commande ?",
            "Bonsoir, Statut de ma livraison",
            "Pardon, Combien de temps reste-t-il merci ?",
            "Pouvez-vous m’aider : Tu pourrais c’est livré quand ?",
            "J’attends un canapé en détail, svp",
            "J’aurais besoin d’un renseignement : Où se trouve ma livraison s’il te plaît ?",
            "S’il te plaît, Je voudrais le transporteur ne m’a pas contacté",
            "S’il te plaît, Tu pourrais quand la livraison aura lieu ?",
            "S’il vous plaît, J’aimerais quand la livraison aura lieu",
            "S’il te plaît, Je voudrais où est mon colis",
            "Pouvez-vous m’aider : Serait-il possible de je veux voir le suivi ?",
            "Pardon, Peux-tu me dire quand j’aurai ma table svp ?",
            "Rebonjour, Tu pourrais j’attends un canapé ?",
            "Rebonjour, Peux-tu où en est ma commande ?",
            "Pouvez-vous m’aider : Est-ce que j’attends un canapé ?",
            "S’il te plaît, Je voudrais ma commande est bloquée",
            "Bonsoir, Serait-il possible de comment suivre la livraison ?",
            "Rebonjour, Je veux suivre ma commande",
            "Bonjour, Est-ce que vous pouvez je n’ai toujours rien reçu ?",
            "Bonsoir, Je voudrais ma commande est bloquée",
            "J’aimerais savoir : Tu pourrais j’attends un canapé ?",
            "J’aurais besoin d’un renseignement : Est-ce que où est mon meuble ?",
            "Pardon, Serait-il possible de où est mon colis ?",
            "Bonsoir, Est-ce que vous pouvez mon colis n’est pas arrivé ?",
            "Petite question : Où en est ma commande s’il vous plaît ?",
            "J’aurais besoin d’un renseignement : Je voudrais statut de ma livraison",
            "Salut, J’aimerais statut de ma livraison",
            "Petite question : Pourriez-vous peux-tu me dire quand j’aurai ma table ?",
            "Petite question : Je veux voir le suivi",
            "Bonjour, Peux-tu suivi de commande ?",
            "Je me permets de vous contacter : Je voudrais combien de temps reste-t-il",
            "Ma commande est partie  étape par étape",
            "Petite question : Tu pourrais ma commande est partie ?",
            "Pardon, Je veux voir le suivi s’il vous plaît",
            "Pouvez-vous m’aider : Tu pourrais statut de ma livraison ?",
            "Pardon, Je cherche à ma commande est bloquée",
            "Petite question : Je voudrais où est mon colis",
            "Rebonjour, J’aimerais combien de temps reste-t-il",
            "J’aurais besoin d’un renseignement : Peux-tu statut de ma livraison ?",
            "Salut, J’aimerais peux-tu me dire quand j’aurai ma table",
            "J’aurais besoin d’un renseignement : Je voudrais je veux voir le suivi",
            "Pourriez-vous mon colis n’est pas arrivé ?",
            "Je voudrais quand vais-je recevoir ma commande",
            "Bonjour, C’est livré quand svp ?",
            "Ma commande est partie ?",
            "J’aurais besoin d’un renseignement : Est-ce que vous pouvez suivi de commande ?",
            "Je me permets de vous contacter : Je voudrais où est mon colis",
            "Pouvez-vous m’aider : Pourriez-vous m’indiquer mon colis n’est pas arrivé ?",
            "Pardon, J’aimerais statut de ma livraison",
            "Excuse-moi, Pourriez-vous combien de temps reste-t-il ?",
            "S’il vous plaît, Pourriez-vous où est mon meuble ?",
            "Pardon, Je voudrais je veux suivre ma commande",
            "Rebonjour, Où est mon colis",
            "S’il vous plaît, Pourriez-vous ma commande est partie ?",
            "Bonjour, Pourriez-vous m’indiquer où en est ma commande ?",
            "Rebonjour, Est-ce que vous pouvez je veux voir le suivi ?",
            "Excuse-moi, Pourriez-vous m’indiquer quand la livraison aura lieu ?",
            "Excuse-moi, Je cherche à peux-tu me dire quand j’aurai ma table",
            "Excuse-moi, J’aimerais où est mon meuble",
            "Je me permets de vous contacter : Je cherche à je n’ai toujours rien reçu",
            "Bonsoir, Tu pourrais où en est ma commande ?"
        ],
        "answer": "Pour suivre votre commande, entrez votre numéro sur la page *Suivi de commande* de mobilia.fr 📦.",
        "action_index": 0
    },
    {
        "question": [
            "S’il te plaît, Je cherche à je veux changer l’adresse de livraison",
            "Pardon, Livraison express disponible stp",
            "J’aimerais savoir : Peux-tu puis-je être livré sur mon lieu de travail ?",
            "Salut, Peux-tu vous livrez en combien de temps ?",
            "Pouvez-vous m’aider : Est-ce que vous faites le montage à la livraison ?",
            "Pardon, Je voudrais quels sont vos délais de livraison",
            "Besoin d’aide pour livrez-vous en belgique",
            "Excuse-moi, Combien coûte la livraison s’il te plaît ?",
            "Livrez-vous à l’étranger  en détail, svp",
            "Pouvez-vous m’aider : Vous livrez à domicile",
            "Petite question : Pourriez-vous vous livrez en combien de temps ?",
            "Bonsoir, Je cherche à vous livrez à domicile",
            "Besoin d’aide pour quels sont vos transporteurs",
            "Je me permets de vous contacter : Tu pourrais est-ce que vous faites le montage à la livraison ?",
            "Je me permets de vous contacter : Pourriez-vous puis-je choisir la date de livraison ?",
            "Salut, Livrez-vous en Belgique s’il vous plaît ?",
            "Est-ce que vous pouvez la livraison est gratuite ?",
            "Pouvez-vous m’aider : Je voudrais puis-je être livré sur mon lieu de travail",
            "Petite question : Est-ce que vous pouvez livrez-vous en belgique ?",
            "Bonjour, Tu pourrais je veux changer l’adresse de livraison ?",
            "J’aurais besoin d’un renseignement : Je cherche à vous livrez à domicile",
            "Tu pourrais avez-vous une option premium ?",
            "S’il te plaît, Tu pourrais livrez-vous le week-end ?",
            "Bonsoir, Pourriez-vous quels sont vos délais de livraison ?",
            "S’il te plaît, Serait-il possible de puis-je être livré sur mon lieu de travail ?",
            "J’aurais besoin d’un renseignement : Pourriez-vous livrez-vous en belgique ?",
            "Bonjour, Je voudrais combien de temps pour un canapé",
            "Rebonjour, J’aimerais je veux changer l’adresse de livraison",
            "Pouvez-vous m’aider : Pourriez-vous m’indiquer combien de temps pour un canapé ?",
            "Bonsoir, Quels sont vos délais de livraison s’il te plaît ?",
            "Bonjour, Est-ce que combien coûte la livraison ?",
            "Pardon, Est-ce que je veux changer l’adresse de livraison ?",
            "Est-ce que vous faites le montage à la livraison  étape par étape",
            "S’il te plaît, Pourriez-vous livrez-vous en belgique ?",
            "Est-ce que puis-je être livré sur mon lieu de travail ?",
            "Salut, Est-ce que livrez-vous le week-end ?",
            "Excuse-moi, Est-ce que est-ce que vous livrez en suisse ?",
            "Pouvez-vous m’aider : Quel est le délai moyen",
            "S’il vous plaît, Je voudrais livrez-vous le week-end",
            "Pardon, J’aimerais avez-vous une option premium",
            "J’aimerais savoir : Pourriez-vous m’indiquer combien de jours pour la livraison ?",
            "Excuse-moi, Pourriez-vous combien de jours pour la livraison ?",
            "J’aurais besoin d’un renseignement : Je cherche à livrez-vous en belgique",
            "Bonjour, Je veux changer l’adresse de livraison",
            "Excuse-moi, Pourriez-vous la livraison est gratuite ?",
            "Pourriez-vous m’indiquer quel est le délai moyen ?",
            "Quel est le délai moyen",
            "S’il te plaît, Je cherche à livrez-vous à l’étranger",
            "Je me permets de vous contacter : Je voudrais combien de jours pour la livraison",
            "Puis-je choisir la date de livraison",
            "S’il vous plaît, Pourriez-vous m’indiquer livrez-vous en belgique ?",
            "Rebonjour, Est-ce que vous pouvez la livraison est gratuite ?",
            "Petite question : Vous livrez en combien de temps",
            "J’aurais besoin d’un renseignement : J’aimerais livrez-vous le week-end",
            "J’aimerais savoir : Je cherche à puis-je être livré sur mon lieu de travail",
            "Pardon, Puis-je choisir la date de livraison ?",
            "Bonjour, Livrez-vous en Belgique s’il vous plaît ?",
            "Salut, Livrez-vous le week-end",
            "Pouvez-vous m’aider : Pourriez-vous m’indiquer livrez-vous en belgique ?",
            "Bonjour, Serait-il possible de je veux changer l’adresse de livraison ?",
            "Pouvez-vous m’aider : Je cherche à quels sont vos transporteurs",
            "Petite question : Combien coûte la livraison ?",
            "Excuse-moi, Je cherche à combien de jours pour la livraison",
            "S’il vous plaît, Pourriez-vous quels sont vos délais de livraison ?",
            "Bonsoir, Est-ce que vous pouvez combien de jours pour la livraison ?",
            "S’il te plaît, Je voudrais vous livrez en combien de temps",
            "S’il vous plaît, La livraison est gratuite stp",
            "J’aimerais savoir : Est-ce que vous livrez en combien de temps ?",
            "Bonsoir, Pourriez-vous je veux changer l’adresse de livraison ?",
            "S’il te plaît, Quels sont vos transporteurs svp",
            "S’il vous plaît, Serait-il possible de est-ce que vous faites le montage à la livraison ?",
            "J’aurais besoin d’un renseignement : Quels sont vos transporteurs svp",
            "Bonjour, Quels sont vos transporteurs",
            "Est-ce que vous pouvez est-ce que vous faites le montage à la livraison ?",
            "Je n’arrive pas à combien de jours pour la livraison , pouvez-vous m’aider ?",
            "Petite question : Peux-tu puis-je choisir la date de livraison ?",
            "J’aimerais savoir : Tu pourrais livrez-vous à l’étranger ?",
            "J’aimerais avez-vous une option premium",
            "Rebonjour, Je voudrais quand vais-je recevoir mon meuble",
            "Bonsoir, Est-ce que livrez-vous le week-end ?"
        ],
        "answer": "Nos livraisons prennent entre 3 et 7 jours ouvrés 🚚. Oui, nous livrons à domicile en France, Belgique et Suisse.",
        "action_index": 0
    },
    {
        "question": [
            "Besoin d’aide pour le montage est impossible",
            "J’aurais besoin d’un renseignement : Tu pourrais comment faire un retour ?",
            "Salut, Pourriez-vous m’indiquer je n’ai pas reçu les bonnes pièces ?",
            "Petite question : Je voudrais comment contacter le service client",
            "S’il te plaît, Pourriez-vous je souhaite un remboursement complet ?",
            "Petite question : Est-ce que je n’ai pas reçu les bonnes pièces ?",
            "Petite question : Est-ce que vous pouvez ma table est rayée ?",
            "Bonjour, Pourriez-vous m’indiquer je veux retourner un produit ?",
            "Excuse-moi, Puis-je renvoyer l’article s’il te plaît ?",
            "J’aurais besoin d’un renseignement : Comment contacter le service client",
            "J’aurais besoin d’un renseignement : Est-ce que vous pouvez je veux retourner un produit ?",
            "J’aimerais comment faire un retour",
            "J’aurais besoin d’un renseignement : Je cherche à je veux retourner un produit",
            "J’aurais besoin d’un renseignement : Tu pourrais le colis est abîmé ?",
            "Pardon, Peux-tu j’ai reçu la mauvaise couleur ?",
            "J’aimerais savoir : Peux-tu j’ai reçu un produit défectueux ?",
            "S’il te plaît, Est-ce que vous pouvez il manque une vis ?",
            "Je me permets de vous contacter : J’aimerais j’ai reçu la mauvaise couleur",
            "Petite question : Pourriez-vous m’indiquer j’ai reçu un produit défectueux ?",
            "Salut, Pourriez-vous m’indiquer j’ai reçu un produit défectueux ?",
            "Bonsoir, J’ai reçu un produit défectueux merci ?",
            "Petite question : Est-ce que vous pouvez comment fonctionne le sav ?",
            "S’il te plaît, Je voudrais comment fonctionne le sav",
            "Petite question : Je veux un échange ?",
            "Je me permets de vous contacter : Le montage est impossible s’il te plaît ?",
            "Salut, Je voudrais je souhaite un remboursement complet",
            "Je me permets de vous contacter : Pourriez-vous le colis est abîmé ?",
            "J’aimerais savoir : Comment fonctionne le SAV ?",
            "Rebonjour, Serait-il possible de puis-je renvoyer l’article ?",
            "Bonsoir, Pourriez-vous je souhaite un remboursement complet ?",
            "Bonsoir, Le montage est impossible s’il te plaît",
            "Pardon, Est-ce que vous pouvez le montage est impossible ?",
            "Petite question : Le meuble ne me plaît pas svp ?",
            "S’il te plaît, Pourriez-vous m’indiquer comment fonctionne le sav ?",
            "S’il te plaît, Mon meuble est cassé merci ?",
            "J’aimerais savoir : Est-ce que j’ai reçu la mauvaise couleur ?",
            "J’aimerais savoir : Tu pourrais le montage est impossible ?",
            "J’aurais besoin d’un renseignement : Je voudrais j’ai reçu la mauvaise couleur",
            "Pardon, Tu pourrais puis-je être remboursé ?",
            "S’il te plaît, Tu pourrais comment fonctionne le sav ?",
            "J’aimerais savoir : Est-ce que vous pouvez je veux un échange ?",
            "Bonjour, Puis-je être remboursé",
            "Pouvez-vous m’aider : J’aimerais je veux changer de couleur",
            "J’aimerais savoir : Le livreur a abîmé mon colis",
            "Pardon, J’aimerais j’ai reçu la mauvaise couleur",
            "J’aurais besoin d’un renseignement : Est-ce que vous pouvez comment fonctionne le sav ?",
            "Est-ce que le montage est impossible ?",
            "Bonjour, J’aimerais je n’ai pas reçu les bonnes pièces",
            "Excuse-moi, J’aimerais je veux un échange",
            "Comment fonctionne le SAV",
            "Salut, Je voudrais le meuble ne me plaît pas",
            "S’il vous plaît, J’ai reçu un produit défectueux merci ?",
            "Je me permets de vous contacter : Est-ce que vous pouvez comment faire un retour ?",
            "Excuse-moi, Pourriez-vous m’indiquer je veux changer de couleur ?",
            "Excuse-moi, Le colis est abîmé",
            "Bonjour, Peux-tu comment contacter le service client ?",
            "Rebonjour, Je voudrais puis-je renvoyer l’article",
            "Rebonjour, Je cherche à puis-je renvoyer l’article",
            "Pouvez-vous m’aider : Peux-tu je n’ai pas reçu les bonnes pièces ?",
            "Excuse-moi, Est-ce que vous pouvez puis-je renvoyer l’article ?",
            "Rebonjour, J’aimerais le livreur a abîmé mon colis",
            "Pardon, Je cherche à il manque une vis",
            "Je me permets de vous contacter : Est-ce que puis-je être remboursé ?",
            "Le livreur a abîmé mon colis en détail, svp",
            "Excuse-moi, Le montage est impossible",
            "Salut, Tu pourrais j’ai un problème avec ma commande ?",
            "Salut, Est-ce que vous pouvez je souhaite un remboursement complet ?",
            "J’aimerais savoir : Pourriez-vous j’ai un problème avec ma commande ?",
            "Je me permets de vous contacter : J’ai reçu un produit défectueux svp",
            "Pouvez-vous m’aider : Est-ce que vous pouvez j’ai un problème avec ma commande ?",
            "Je n’arrive pas à je veux retourner un produit, pouvez-vous m’aider ?",
            "Bonjour, Est-ce que vous pouvez il manque une vis ?",
            "J’aurais besoin d’un renseignement : Je veux un échange",
            "Rebonjour, Est-ce que vous pouvez le meuble ne me plaît pas ?",
            "S’il vous plaît, J’aimerais j’ai un problème avec ma commande",
            "Pouvez-vous m’aider : Tu pourrais je souhaite un remboursement complet ?",
            "J’aurais besoin d’un renseignement : Est-ce que vous pouvez je n’ai pas reçu les bonnes pièces ?",
            "J’aimerais savoir : Je voudrais comment fonctionne le sav",
            "S’il vous plaît, Peux-tu puis-je être remboursé ?",
            "Pouvez-vous m’aider : Comment contacter le service client ?"
        ],
        "answer": "Pas d’inquiétude ! Contactez notre service après-vente via le formulaire *Assistance Mobilia*, nous prendrons tout en charge 🔧.",
        "action_index": 0
    },
    {
        "question": [
            "Bonjour, Tu pourrais quel canapé pour un grand salon ?",
            "Petite question : Peux-tu j’hésite entre deux modèles ?",
            "Salut, Est-ce que vous pouvez tu as des idées déco ?",
            "J’aimerais savoir : Je cherche à quelle couleur irait dans un salon clair",
            "Pardon, Est-ce que vous pouvez tu me conseilles quel style scandinave ?",
            "S’il vous plaît, Est-ce que peux-tu me conseiller ?",
            "Pardon, Tu as des idées déco",
            "S’il vous plaît, Peux-tu quel style choisir ?",
            "J’aimerais savoir : Je voudrais peux-tu me conseiller",
            "Pouvez-vous m’expliquer comment quelle couleur irait dans un salon clair  ?",
            "Rebonjour, Je cherche un meuble minimaliste s’il te plaît ?",
            "Bonjour, Je cherche à quel luminaire pour un bureau",
            "Bonsoir, Tu as des idées déco merci",
            "S’il vous plaît, Je cherche à j’aime le bois clair, tu proposes quoi",
            "Je me permets de vous contacter : Tu pourrais tu peux m’aider à harmoniser les couleurs ?",
            "J’aimerais savoir : Est-ce que vous pouvez quelle couleur irait dans un salon clair ?",
            "J’aimerais savoir : Pourriez-vous m’indiquer j’aime le bois clair, tu proposes quoi ?",
            "J’aimerais savoir : Pourriez-vous m’indiquer je cherche un meuble minimaliste ?",
            "Tu me conseilles quel style scandinave  quand vous pouvez",
            "Bonjour, Je voudrais quelle table pour un salon moderne",
            "Pouvez-vous m’aider : Est-ce que quel canapé pour un grand salon ?",
            "Bonjour, Quel canapé pour un petit salon stp ?",
            "S’il te plaît, Peux-tu quelle table pour un salon moderne ?",
            "Petite question : Pourriez-vous quelle couleur irait dans un salon clair ?",
            "J’aurais besoin d’un renseignement : Je voudrais j’ai un salon beige, que mettre",
            "S’il vous plaît, Je cherche un meuble minimaliste s’il te plaît ?",
            "Je me permets de vous contacter : Est-ce que quel bureau pour télétravailler ?",
            "Salut, J’aimerais je cherche un meuble minimaliste",
            "Pardon, Serait-il possible de quel luminaire pour un bureau ?",
            "Excuse-moi, Pourriez-vous tu as des idées déco ?",
            "S’il te plaît, Tu pourrais tu peux m’aider à harmoniser les couleurs ?",
            "Excuse-moi, Quel canapé pour un petit salon",
            "J’aimerais savoir : J’aimerais aide-moi à choisir un meuble",
            "Bonsoir, Quelle couleur irait dans un salon clair s’il te plaît",
            "Je me permets de vous contacter : Est-ce que vous pouvez quel luminaire pour un bureau ?",
            "Bonjour, J’aime le bois clair, tu proposes quoi ?",
            "Je n’arrive pas à peux-tu me conseiller , pouvez-vous m’aider ?",
            "Pouvez-vous m’aider : J’aimerais quel canapé pour un petit salon",
            "S’il vous plaît, Est-ce que j’aime le bois clair, tu proposes quoi ?",
            "J’aimerais tu me conseilles quel style scandinave",
            "S’il vous plaît, Tu pourrais quel canapé pour un petit salon ?",
            "Bonjour, Est-ce que quelle couleur irait dans un salon clair ?",
            "S’il te plaît, Est-ce que tu me conseilles quel style scandinave ?",
            "J’aurais besoin d’un renseignement : Pourriez-vous je veux une ambiance industrielle ?",
            "Rebonjour, Quel style choisir",
            "J’aimerais savoir : J’aime le bois clair, tu proposes quoi merci",
            "Salut, Peux-tu quelle table pour un salon moderne ?",
            "Pouvez-vous m’aider : Tu peux m’aider pour ma déco",
            "S’il vous plaît, Serait-il possible de j’aime le bois clair, tu proposes quoi ?",
            "Pardon, Pourriez-vous m’indiquer j’hésite entre deux modèles ?",
            "Je me permets de vous contacter : Quel canapé pour un petit salon",
            "Je me permets de vous contacter : Je voudrais quel canapé pour un petit salon",
            "J’aimerais savoir : Je cherche à j’hésite entre deux modèles",
            "Quelle table pour un salon moderne stp ?",
            "Je me permets de vous contacter : Quelle table pour un salon moderne stp ?",
            "J’aurais besoin d’un renseignement : J’aime le bois clair, tu proposes quoi",
            "Peux-tu me conseiller  en détail, svp",
            "Excuse-moi, Pourriez-vous quelle table pour un salon moderne ?",
            "Serait-il possible de tu me conseilles quel style scandinave ?",
            "Pardon, Je voudrais tu as des idées déco",
            "S’il te plaît, Tu pourrais j’ai un salon beige, que mettre ?",
            "S’il vous plaît, Quel canapé pour un petit salon ?",
            "J’aurais besoin d’un renseignement : Pourriez-vous m’indiquer tu peux m’aider à harmoniser les couleurs ?",
            "J’aurais besoin d’un renseignement : Peux-tu quel bureau pour télétravailler ?",
            "Pardon, Est-ce que j’hésite entre deux modèles ?",
            "Excuse-moi, Aide-moi à choisir un meuble ?",
            "J’aimerais savoir : Est-ce que tu as des idées déco ?",
            "J’aurais besoin d’un renseignement : Quel canapé pour un grand salon svp",
            "Quel canapé pour un petit salon  rapidement, s’il vous plaît",
            "Excuse-moi, Je voudrais quel luminaire pour un bureau",
            "Rebonjour, Peux-tu me conseiller",
            "J’aimerais savoir : Quel luminaire pour un bureau svp ?",
            "J’aurais besoin d’un renseignement : Est-ce que je veux une ambiance industrielle ?",
            "J’aimerais savoir : Pourriez-vous m’indiquer tu peux m’aider à harmoniser les couleurs ?",
            "J’aimerais savoir : Tu pourrais quel style est à la mode ?",
            "Excuse-moi, Je voudrais quelle table pour un salon moderne",
            "Je me permets de vous contacter : Tu as des idées déco merci",
            "Salut, Serait-il possible de quel canapé pour un grand salon ?",
            "Salut, Quel luminaire pour un bureau ?",
            "Salut, J’aimerais quelle matière est la plus solide"
        ],
        "answer": "Avec plaisir 🎨 ! Pour un salon clair, privilégiez les tons beiges et le bois clair. Pour un petit espace, optez pour du mobilier modulable.",
        "action_index": 0
    },
    {
        "question": [
            "Salut, Est-ce qu’il y a des offres spéciales stp ?",
            "Pardon, Je voudrais je veux une remise",
            "C’est cher",
            "Je me permets de vous contacter : Je cherche à y a-t-il des soldes",
            "S’il te plaît, Serait-il possible de vous avez des promotions ?",
            "Bonjour, Serait-il possible de c’est moins cher en magasin ?",
            "Pardon, C’est cher ?",
            "Salut, C’est cher ?",
            "Je me permets de vous contacter : J’aimerais faites-vous des réductions",
            "Rebonjour, Pourriez-vous faites-vous des réductions ?",
            "Excuse-moi, Vous avez des codes promo merci",
            "S’il te plaît, Je cherche à les frais de livraison sont inclus",
            "Pardon, Serait-il possible de y a-t-il des ventes privées ?",
            "Pouvez-vous m’aider : C’est cher",
            "Petite question : Pourriez-vous m’indiquer quels sont vos prix ?",
            "Quels sont vos prix  rapidement, s’il vous plaît",
            "Bonjour, Vos prix incluent la TVA",
            "S’il te plaît, Y a-t-il des ventes privées svp",
            "J’aurais besoin d’un renseignement : Serait-il possible de puis-je avoir un bon de réduction ?",
            "Pourriez-vous m’indiquer quel est le prix d’un canapé ?",
            "Pardon, Je cherche à faites-vous des réductions",
            "J’aimerais savoir : Pourriez-vous m’indiquer vous avez des promotions ?",
            "Bonjour, Est-ce que quels sont vos prix ?",
            "Pouvez-vous m’aider : Y a-t-il des ventes privées ?",
            "S’il te plaît, Je cherche à est-ce qu’il y a des offres spéciales",
            "Je me permets de vous contacter : Comment profiter d’une promo ?",
            "Petite question : Peux-tu quand sont les soldes ?",
            "Pardon, Quels sont vos prix s’il te plaît ?",
            "Salut, Quand sont les soldes",
            "Peux-tu est-ce qu’il y a des offres spéciales ?",
            "Pouvez-vous m’expliquer comment faites-vous des réductions  ?",
            "S’il vous plaît, Pourriez-vous combien coûte une table en bois ?",
            "Petite question : Vos prix incluent la TVA",
            "S’il vous plaît, Serait-il possible de vous avez des promotions ?",
            "Combien coûte une table en bois  en détail, svp",
            "J’aimerais savoir : Est-ce qu’il y a des offres spéciales ?",
            "Pouvez-vous m’aider : Les frais de livraison sont inclus stp ?",
            "S’il te plaît, Tu pourrais le montage est compris ?",
            "Rebonjour, Est-ce que vous pouvez vos prix incluent la tva ?",
            "Bonjour, Est-ce que vous pouvez vos prix incluent la tva ?",
            "S’il vous plaît, C’est moins cher en magasin ?",
            "Bonjour, Faites-vous des réductions ?",
            "Salut, Je voudrais quels sont vos prix",
            "Rebonjour, Le montage est compris",
            "Excuse-moi, Est-ce que vous pouvez puis-je avoir un bon de réduction ?",
            "Rebonjour, J’aimerais vous faites le black friday",
            "Salut, Pourriez-vous m’indiquer quel est le prix d’un canapé ?",
            "Bonsoir, Pourriez-vous m’indiquer vous avez des promotions ?",
            "Je me permets de vous contacter : Je voudrais c’est cher",
            "Bonjour, Le montage est compris",
            "S’il te plaît, Je voudrais vous avez des codes promo",
            "Bonsoir, Faites-vous des réductions svp",
            "J’aurais besoin d’un renseignement : Je voudrais je veux une remise",
            "Bonsoir, Peux-tu y a-t-il des soldes ?",
            "Salut, J’aimerais faites-vous des réductions",
            "Rebonjour, Serait-il possible de le montage est compris ?",
            "Bonjour, Je voudrais quand sont les soldes",
            "Salut, Je veux une remise ?",
            "Petite question : C’est cher s’il vous plaît",
            "Pardon, Est-ce que quand sont les soldes ?",
            "Rebonjour, Serait-il possible de quand sont les soldes ?",
            "J’aurais besoin d’un renseignement : Les frais de livraison sont inclus stp",
            "Petite question : Je voudrais je veux une remise",
            "Bonsoir, Pourriez-vous m’indiquer faites-vous des réductions ?",
            "Pardon, Quel est le prix d’un canapé ?",
            "Bonjour, Quand sont les soldes ?",
            "Pardon, Pourriez-vous vous faites le black friday ?",
            "Vous avez des codes promo  au plus vite",
            "Pouvez-vous m’aider : Pourriez-vous m’indiquer vous avez des codes promo ?",
            "Salut, Vous avez des codes promo merci",
            "J’aimerais savoir : Je voudrais faites-vous des réductions",
            "Le montage est compris  maintenant ?",
            "S’il te plaît, Je cherche à c’est moins cher en magasin",
            "Excuse-moi, Je voudrais quel est le prix d’un canapé",
            "Petite question : Combien coûte une table en bois svp",
            "Bonjour, J’aimerais y a-t-il des ventes privées",
            "J’aurais besoin d’un renseignement : Je cherche à combien coûte une table en bois",
            "Je me permets de vous contacter : Puis-je avoir un bon de réduction ?",
            "Petite question : J’aimerais vous faites le black friday",
            "Je me permets de vous contacter : Vos prix incluent la TVA merci ?"
        ],
        "answer": "Nos prix varient selon la gamme 💶. Consultez mobilia.fr pour voir les promos et nos soldes en cours !",
        "action_index": 0
    },
    {
        "question": [
            "Bonjour, Je cherche à vous acceptez le paiement en crypto",
            "S’il vous plaît, Je veux changer de mode de paiement",
            "Excuse-moi, Acceptez-vous Mastercard ?",
            "S’il te plaît, Je peux payer en chèque",
            "J’aimerais savoir : Serait-il possible de vous acceptez apple pay ?",
            "Bonjour, Puis-je avoir une facture stp",
            "Petite question : Acceptez-vous Mastercard s’il te plaît ?",
            "Je me demandais : je veux payer plus tard ?",
            "Besoin d’aide pour puis-je avoir une facture",
            "S’il vous plaît, Vous prenez les cartes Visa s’il vous plaît ?",
            "Bonsoir, Peux-tu je veux changer de mode de paiement ?",
            "Rebonjour, Vous acceptez le paiement en crypto s’il te plaît",
            "S’il te plaît, Je veux payer en 3 fois",
            "J’aimerais savoir : Je voudrais puis-je utiliser ma carte cadeau",
            "Pouvez-vous m’aider : Je cherche à puis-je avoir une facture",
            "J’aurais besoin d’un renseignement : Acceptez-vous PayPal",
            "Pardon, Pourriez-vous puis-je payer en plusieurs fois ?",
            "S’il vous plaît, Tu pourrais puis-je payer en plusieurs fois ?",
            "Rebonjour, Peux-tu je peux payer par virement ?",
            "J’aimerais le paiement se fait comment",
            "Pouvez-vous m’aider : Peux-tu le paiement est bien validé ?",
            "S’il te plaît, Vous prenez les cartes Visa",
            "Pouvez-vous m’aider : Je veux changer de mode de paiement ?",
            "Je peux payer par virement  rapidement, s’il vous plaît",
            "Bonjour, Je voudrais quels moyens de paiement acceptez-vous",
            "Petite question : Est-ce que vous acceptez le paiement en crypto ?",
            "S’il vous plaît, Pourriez-vous m’indiquer vous prenez les cartes visa ?",
            "J’aimerais savoir : Puis-je payer en plusieurs fois ?",
            "Excuse-moi, Pourriez-vous vous acceptez apple pay ?",
            "Pardon, Est-ce que vous pouvez le paiement a échoué ?",
            "Rebonjour, Le paiement se fait comment svp",
            "Salut, Est-ce que je peux payer en chèque ?",
            "Je peux payer par virement ?",
            "S’il vous plaît, Est-ce que vous pouvez puis-je payer à la livraison ?",
            "Bonsoir, Quels moyens de paiement acceptez-vous svp ?",
            "Serait-il possible de je peux payer par virement ?",
            "J’aurais besoin d’un renseignement : J’aimerais je peux payer par virement",
            "Je me permets de vous contacter : Vous acceptez le paiement en crypto",
            "J’aurais besoin d’un renseignement : Acceptez-vous PayPal ?",
            "S’il vous plaît, Puis-je payer en plusieurs fois",
            "Bonjour, Je peux payer en chèque stp",
            "J’aimerais savoir : Puis-je avoir une facture ?",
            "J’aimerais savoir : Je cherche à le paiement a échoué",
            "Puis-je payer à la livraison  en détail, svp",
            "Salut, Serait-il possible de puis-je payer en plusieurs fois ?",
            "J’aimerais savoir : Pourriez-vous m’indiquer vous acceptez apple pay ?",
            "Pardon, Quels moyens de paiement acceptez-vous svp ?",
            "Je me permets de vous contacter : Est-ce que vous pouvez je peux payer en chèque ?",
            "J’aimerais savoir : Je cherche à je veux payer plus tard",
            "Bonjour, Est-ce que je veux payer plus tard ?",
            "Peux-tu je veux payer en 3 fois ?",
            "Je cherche à vous prenez les cartes visa",
            "Bonjour, J’aimerais puis-je payer à la livraison",
            "J’aurais besoin d’un renseignement : Est-ce que je veux payer en 3 fois ?",
            "S’il te plaît, Pourriez-vous puis-je utiliser ma carte cadeau ?",
            "Excuse-moi, Pourriez-vous m’indiquer vous prenez les cartes visa ?",
            "Salut, Serait-il possible de le paiement a échoué ?",
            "S’il te plaît, Est-ce que vous pouvez puis-je payer en plusieurs fois ?",
            "Petite question : Tu pourrais je veux payer en 3 fois ?",
            "Le paiement a échoué quand vous pouvez",
            "Petite question : Peux-tu acceptez-vous mastercard ?",
            "Je me permets de vous contacter : Serait-il possible de je veux changer de mode de paiement ?",
            "Petite question : Est-ce que vous pouvez vous prenez les cartes visa ?",
            "Excuse-moi, Est-ce que vous pouvez quels moyens de paiement acceptez-vous ?",
            "Bonsoir, Le paiement est bien validé merci ?",
            "J’aimerais savoir : Est-ce que vous pouvez je veux payer plus tard ?",
            "Bonsoir, Vous acceptez Apple Pay",
            "J’aimerais savoir : Quels moyens de paiement acceptez-vous svp ?",
            "Salut, Peux-tu puis-je avoir une facture ?",
            "Bonsoir, Peux-tu le paiement a échoué ?",
            "J’aurais besoin d’un renseignement : Pourriez-vous m’indiquer le paiement est bien validé ?",
            "Bonsoir, Est-ce que vous acceptez le paiement en crypto ?",
            "J’aurais besoin d’un renseignement : Puis-je utiliser ma carte cadeau svp",
            "Bonsoir, Acceptez-vous PayPal ?",
            "Pardon, Serait-il possible de vous acceptez le paiement en crypto ?",
            "Pouvez-vous m’aider : Serait-il possible de je veux changer de mode de paiement ?",
            "Pouvez-vous m’aider : Je voudrais puis-je payer à la livraison",
            "Petite question : Tu pourrais vous acceptez le paiement en crypto ?",
            "J’aurais besoin d’un renseignement : Tu pourrais puis-je avoir une facture ?",
            "Salut, Peux-tu quels moyens de paiement acceptez-vous ?"
        ],
        "answer": "Nous acceptons carte bancaire, PayPal et paiement en 3x sans frais 💳.",
        "action_index": 0
    },
    {
        "question": [
            "Pardon, Adresse Mobilia ?",
            "J’aurais besoin d’un renseignement : Est-ce que avez-vous un tchat humain ?",
            "Rebonjour, Tu pourrais vous êtes ouverts le dimanche ?",
            "Rebonjour, Tu pourrais quels sont vos horaires ?",
            "Rebonjour, Je voudrais adresse mobilia",
            "Petite question : Je voudrais je veux prendre rendez-vous",
            "Bonjour, Adresse Mobilia ?",
            "S’il vous plaît, Pourriez-vous m’indiquer où se trouve votre boutique ?",
            "Pouvez-vous m’aider : Je veux parler à un humain",
            "Pardon, Est-ce que vous pouvez pouvez-vous m’appeler ?",
            "Pardon, Peux-tu adresse mobilia ?",
            "J’aurais besoin d’un renseignement : Serait-il possible de pouvez-vous m’appeler ?",
            "Pouvez-vous m’aider : J’aimerais je veux écrire un mail",
            "Bonsoir, Comment vous contacter ?",
            "Petite question : Est-ce que vous pouvez quels sont vos horaires ?",
            "Rebonjour, J’aimerais je veux parler à un humain",
            "J’aimerais savoir : Avez-vous un numéro de téléphone ?",
            "Quels sont vos horaires  étape par étape",
            "Pouvez-vous m’aider : Est-ce que vous pouvez vous êtes ouverts le dimanche ?",
            "Petite question : Je veux parler à un humain",
            "S’il te plaît, J’aimerais le service client est ouvert",
            "Bonjour, Je cherche à adresse mobilia",
            "S’il te plaît, J’aimerais vous êtes ouverts le dimanche",
            "Excuse-moi, Peux-tu je veux parler à un humain ?",
            "J’aimerais savoir : Tu pourrais comment parler à un conseiller ?",
            "Rebonjour, Je cherche à je peux passer au magasin",
            "Petite question : Est-ce que avez-vous un magasin à paris ?",
            "Rebonjour, Je cherche à le service client est ouvert",
            "Bonjour, Tu pourrais je veux prendre rendez-vous ?",
            "Pardon, Peux-tu comment vous contacter ?",
            "Je me permets de vous contacter : Serait-il possible de adresse mobilia ?",
            "Pouvez-vous m’aider : Pourriez-vous avez-vous un numéro de téléphone ?",
            "Salut, Je voudrais je veux l’adresse du magasin de bordeaux",
            "J’aurais besoin d’un renseignement : Avez-vous un magasin à Paris",
            "S’il vous plaît, Pourriez-vous m’indiquer avez-vous un showroom ?",
            "J’aurais besoin d’un renseignement : Je voudrais avez-vous un showroom",
            "Rebonjour, Pourriez-vous vous êtes ouverts le dimanche ?",
            "J’aurais besoin d’un renseignement : Je peux passer au magasin s’il vous plaît ?",
            "Pardon, Je veux prendre rendez-vous ?",
            "Besoin d’aide pour où sont vos magasins",
            "Petite question : Serait-il possible de avez-vous un magasin à paris ?",
            "Petite question : Tu pourrais je veux parler à un humain ?",
            "Bonsoir, Tu pourrais pouvez-vous m’appeler ?",
            "Je me permets de vous contacter : J’aimerais avez-vous un magasin à paris",
            "Excuse-moi, Je voudrais où se trouve votre boutique",
            "Bonjour, Est-ce que pouvez-vous m’appeler ?",
            "Excuse-moi, Je voudrais quels sont vos horaires",
            "Bonsoir, Serait-il possible de vous êtes ouverts le dimanche ?",
            "Salut, J’aimerais avez-vous un showroom",
            "Pouvez-vous m’aider : Avez-vous un showroom ?",
            "Rebonjour, Je peux passer au magasin",
            "Petite question : Je cherche à je veux l’adresse du magasin de bordeaux",
            "Salut, Peux-tu je veux prendre rendez-vous ?",
            "S’il te plaît, Je voudrais je veux écrire un mail",
            "Pouvez-vous m’expliquer comment vous êtes ouverts le dimanche  ?",
            "Rebonjour, Est-ce que où sont vos magasins ?",
            "Rebonjour, Tu pourrais comment vous contacter ?",
            "Tu pourrais pouvez-vous me rappeler ?",
            "S’il vous plaît, Je cherche à je veux venir sur place",
            "S’il vous plaît, Est-ce que pouvez-vous me rappeler ?",
            "Bonjour, Je cherche à je peux passer au magasin",
            "S’il vous plaît, Je voudrais avez-vous un tchat humain",
            "S’il te plaît, Tu pourrais pouvez-vous m’appeler ?",
            "S’il vous plaît, Pourriez-vous avez-vous un showroom ?",
            "Petite question : Avez-vous un magasin à Paris s’il vous plaît ?",
            "Excuse-moi, Tu pourrais où sont vos magasins ?",
            "Excuse-moi, Où sont vos magasins",
            "Bonsoir, Serait-il possible de je veux prendre rendez-vous ?",
            "Excuse-moi, Le service client est ouvert svp ?",
            "Bonsoir, Je voudrais avez-vous un magasin à paris",
            "Excuse-moi, Où se trouve votre boutique merci",
            "Bonjour, Peux-tu le service client est ouvert ?",
            "Salut, Je cherche à je peux passer au magasin",
            "Adresse Mobilia merci",
            "Pardon, Je veux parler à un humain ?",
            "Excuse-moi, Le service client est ouvert",
            "Quels sont vos horaires",
            "Salut, Serait-il possible de je veux l’adresse du magasin de bordeaux ?",
            "Excuse-moi, Je cherche à avez-vous un showroom",
            "Je me permets de vous contacter : Est-ce que comment vous contacter ?"
        ],
        "answer": "Notre service client est joignable du lundi au samedi de 9h à 19h au 09 72 00 00 00 ☎️ ou en boutique à Bordeaux et Paris.",
        "action_index": 0
    },
    {
        "question": [
            "Je me permets de vous contacter : Merci à toi stp",
            "Bonjour, Merci ?",
            "Bonjour, Pourriez-vous m’indiquer merci d’avance ?",
            "Top merci quand vous pouvez",
            "J’aimerais savoir : Merci d’avance",
            "Petite question : Serait-il possible de je te remercie encore ?",
            "J’aimerais savoir : Peux-tu super merci ?",
            "Je cherche à merci du renseignement",
            "Pouvez-vous m’aider : Est-ce que parfait merci ?",
            "J’aimerais savoir : Je te remercie encore",
            "Excuse-moi, Tu pourrais merci à toi ?",
            "Petite question : Tu pourrais tu m’as bien aidé ?",
            "Je me permets de vous contacter : T’es super",
            "Petite question : Est-ce que vous pouvez top merci ?",
            "Rebonjour, C’est top",
            "Pardon, Est-ce que tu m’as bien aidé ?",
            "J’aimerais savoir : Est-ce que vous pouvez merci beaucoup ?",
            "S’il te plaît, Pourriez-vous top merci ?",
            "S’il te plaît, Je cherche à merci mobiliabot",
            "J’aurais besoin d’un renseignement : Tu pourrais t’es super ?",
            "Pardon, Pourriez-vous trop bien ?",
            "Rebonjour, Je voudrais merci",
            "Je me permets de vous contacter : Je voudrais merci beaucoup",
            "S’il te plaît, C’est gentil ?",
            "S’il te plaît, Pourriez-vous m’indiquer merci du renseignement ?",
            "Pouvez-vous m’aider : Je cherche à parfait merci",
            "Je te remercie encore quand vous pouvez",
            "Je me permets de vous contacter : Je cherche à super merci",
            "Bonsoir, Est-ce que merci du renseignement ?",
            "J’aurais besoin d’un renseignement : Tu pourrais c’est top ?",
            "Est-ce que merci d’avance ?",
            "Je me permets de vous contacter : Merci MobiliaBot svp",
            "J’aurais besoin d’un renseignement : Pourriez-vous merci du renseignement ?",
            "Pouvez-vous m’aider : Merci pour tes conseils stp",
            "S’il te plaît, Pourriez-vous merci d’avance ?",
            "J’aimerais savoir : Je cherche à merci pour tout",
            "J’aurais besoin d’un renseignement : Est-ce que vous pouvez merci ?",
            "Je voudrais merci pour tes conseils",
            "Petite question : Tu pourrais je te remercie encore ?",
            "Bonjour, Je te remercie encore ?",
            "Pardon, Trop bien",
            "Bonsoir, Est-ce que vous pouvez merci beaucoup ?",
            "T’es super s’il vous plaît ?",
            "Rebonjour, J’aimerais merci",
            "S’il vous plaît, Merci",
            "Petite question : Est-ce que vous pouvez merci infiniment ?",
            "J’aurais besoin d’un renseignement : Je voudrais je te remercie encore",
            "Est-ce que vous pouvez merci du renseignement ?",
            "Bonjour, Super merci",
            "Je me permets de vous contacter : Je cherche à c’est top",
            "Pardon, Merci d’avance s’il te plaît",
            "Je voudrais merci à toi",
            "Pouvez-vous m’aider : Trop bien stp ?",
            "Pouvez-vous m’aider : Peux-tu je te remercie ?",
            "Pouvez-vous m’aider : C’est top",
            "Je n’arrive pas à merci à toi, pouvez-vous m’aider ?",
            "J’aimerais savoir : Je voudrais t’es super",
            "Bonsoir, Je cherche à merci pour tes conseils",
            "S’il vous plaît, Tu pourrais t’es super ?",
            "Salut, Merci du renseignement ?",
            "J’aurais besoin d’un renseignement : Est-ce que merci pour ton aide ?",
            "Excuse-moi, Je voudrais merci pour tout",
            "Bonjour, Je voudrais top merci",
            "S’il vous plaît, Pourriez-vous m’indiquer merci beaucoup ?",
            "S’il vous plaît, Merci à toi",
            "Pardon, Merci pour tes conseils s’il vous plaît ?",
            "J’aurais besoin d’un renseignement : Je cherche à merci pour tes conseils",
            "Je n’arrive pas à merci mobiliabot, pouvez-vous m’aider ?",
            "Rebonjour, Est-ce que vous pouvez je te remercie ?",
            "Rebonjour, Pourriez-vous m’indiquer merci à toi ?",
            "J’aimerais merci pour tes conseils",
            "S’il vous plaît, Pourriez-vous m’indiquer merci pour tout ?",
            "Je cherche à je te remercie",
            "J’aimerais savoir : J’aimerais merci mobiliabot",
            "S’il te plaît, Top merci stp ?",
            "Pardon, Merci d’avance ?",
            "Bonjour, Serait-il possible de merci pour tes conseils ?",
            "Salut, Est-ce que vous pouvez merci ?",
            "Rebonjour, Pourriez-vous m’indiquer merci d’avance ?",
            "J’aurais besoin d’un renseignement : Peux-tu t’es super ?"
        ],
        "answer": "Avec grand plaisir 😊. N’hésitez pas à revenir si vous avez d’autres questions !",
        "action_index": 0
    },
    {
        "question": [
            "Salut, Bonne soirée svp",
            "Excuse-moi, Je cherche à je n’ai plus de question",
            "S’il vous plaît, À demain stp",
            "Bonsoir, Tu pourrais je clos ici ?",
            "S’il vous plaît, Je cherche à bonne nuit",
            "S’il vous plaît, Pourriez-vous je te laisse ?",
            "Peux-tu fin de chat ?",
            "Je voudrais je clos ici",
            "Je me permets de vous contacter : Tu pourrais je pars ?",
            "Je me permets de vous contacter : Je te laisse stp ?",
            "J’aimerais savoir : Pourriez-vous m’indiquer fin de chat ?",
            "Rebonjour, Je cherche à bye bye",
            "Rebonjour, Est-ce que je quitte la conversation ?",
            "S’il vous plaît, Tu pourrais je clos ici ?",
            "Salut, Est-ce que à plus tard ?",
            "J’aurais besoin d’un renseignement : Pourriez-vous merci, c’est tout ?",
            "S’il vous plaît, Je cherche à ciao",
            "Salut, Est-ce que on se revoit bientôt ?",
            "Bonjour, Peux-tu merci, c’est tout ?",
            "Salut, Je voudrais c’est fini pour moi",
            "Ciao au plus vite",
            "J’aimerais savoir : Pourriez-vous m’indiquer je te laisse ?",
            "À demain stp",
            "Bonjour, Tu pourrais bonne soirée ?",
            "Rebonjour, Est-ce que vous pouvez bonne nuit ?",
            "S’il vous plaît, Pourriez-vous m’indiquer bye bye ?",
            "Salut, J’aimerais à la prochaine",
            "J’aurais besoin d’un renseignement : Serait-il possible de je quitte la conversation ?",
            "À bientôt rapidement, s’il vous plaît",
            "Bonsoir, J’aimerais je quitte la conversation",
            "Pouvez-vous m’aider : Je clos ici ?",
            "Pardon, Je cherche à au revoir",
            "J’aimerais savoir : Je pars s’il te plaît ?",
            "Pardon, Peux-tu c’est fini pour moi ?",
            "Petite question : Peux-tu on se revoit bientôt ?",
            "S’il te plaît, J’aimerais bonne soirée",
            "Rebonjour, À la prochaine s’il te plaît",
            "S’il te plaît, Je cherche à je clos ici",
            "Bonsoir, Pourriez-vous à la prochaine ?",
            "Je me permets de vous contacter : Je cherche à bonne journée à toi",
            "Rebonjour, Tu pourrais à plus tard ?",
            "Pardon, Je voudrais bye bye",
            "Je me permets de vous contacter : Je voudrais je quitte la conversation",
            "S’il vous plaît, Pourriez-vous m’indiquer bonne journée à toi ?",
            "J’aurais besoin d’un renseignement : Au revoir",
            "Bonjour, Pourriez-vous m’indiquer au revoir ?",
            "Je me permets de vous contacter : Est-ce que vous pouvez à bientôt ?",
            "S’il vous plaît, Serait-il possible de à bientôt ?",
            "Pourriez-vous à bientôt ?",
            "Bonjour, Pourriez-vous à bientôt ?",
            "Petite question : Peux-tu à la prochaine ?",
            "Pouvez-vous m’aider : Je cherche à bonne nuit",
            "Salut, Pourriez-vous m’indiquer au revoir ?",
            "Bonsoir, Est-ce que vous pouvez ciao ?",
            "J’aimerais savoir : J’aimerais au revoir",
            "Bonsoir, Est-ce que vous pouvez je clos ici ?",
            "J’aimerais savoir : Pourriez-vous je pars ?",
            "Pardon, Pourriez-vous m’indiquer bonne journée à toi ?",
            "Bonjour, On se revoit bientôt",
            "Excuse-moi, J’aimerais je quitte la conversation",
            "S’il vous plaît, Serait-il possible de ciao ?",
            "Pardon, J’aimerais à la prochaine",
            "Je te laisse ?",
            "J’aurais besoin d’un renseignement : Est-ce que vous pouvez je quitte la conversation ?",
            "S’il te plaît, À demain",
            "Pouvez-vous m’aider : Je voudrais à la prochaine",
            "Pardon, Je cherche à à bientôt",
            "S’il te plaît, Serait-il possible de bye bye ?",
            "Pouvez-vous m’aider : À la prochaine ?",
            "Pardon, J’aimerais je te laisse",
            "Bye bye au plus vite",
            "S’il te plaît, Tu pourrais je pars ?",
            "Bonne nuit en détail, svp",
            "Je voudrais je quitte la conversation",
            "Excuse-moi, Je cherche à bonne nuit",
            "J’aurais besoin d’un renseignement : Je cherche à au revoir",
            "Bonjour, Je voudrais à plus tard",
            "Petite question : Est-ce que bonne soirée ?",
            "Pardon, Pourriez-vous m’indiquer je pars ?",
            "Petite question : Je te laisse stp ?"
        ],
        "answer": "À très bientôt chez Mobilia 🪑 !",
        "action_index": 1
    }
]